spring.application.name=PolyFroms

server.port=8080
## default connection pool
spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

## PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/polyforms
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# create and drop table, good for testing, production set to none or comment it
spring.jpa.hibernate.ddl-auto=update



# ############# GITHUB OAUTH #####################
spring.security.oauth2.client.registration.github.client-id=Ov23liAW8hag3ECTFmeB
spring.security.oauth2.client.registration.github.client-secret=29476561323c51620eef257e101ddbcf2f764bd6
spring.security.oauth2.client.registration.github.scope=user:email
spring.security.oauth2.client.registration.github.redirect-uri=http://localhost:8080/login/oauth2/code/github
spring.security.oauth2.client.provider.github.authorization-uri=https://github.com/login/oauth/authorize
spring.security.oauth2.client.provider.github.token-uri=https://github.com/login/oauth/access_token
spring.security.oauth2.client.provider.github.user-info-uri=https://api.github.com/user
spring.security.oauth2.client.provider.github.user-name-attribute=id
